[package]
name = "hyperlightz-bridge"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
hyperlight-host = { git = "https://github.com/cataggar/hyperlight", rev = "89792856686085ddb12b11b395a1d543ccd8fb07", default-features = false, features = ["kvm"] }
